### ISSUE TITLE
git conventions / contribution guidelines

### ISSUE THREAD

**Issue by derek-adair** [derek-adair/nflgame#16]
Also looking for suggestions here.

Things to agree upon;

- [ ] .gitignore
- [ ] Are we picky about how pull requests work?
- [ ] Any python conventions?
- [ ] Should we start asking for tests w/ pull requests? :smiling_imp:

**Comment by mickeelm** [comment]
My five cents:

*.gitigore* - I took the liberty of updating it with my last PR, since .pyc-files werent ignored. I don't necessarily see that we need a policy for this, I think that if for instance a contributor uses an IDE that adds some metadata-folder that isn't included in `.gitignore` today, then I'd welcome that add.

*Are we picky about how pull requests work?* I think that best practice is to have the PR relate to an issue. Like it's great if the discussion on whether to or whether not to include certain functionality has already been made prior to submitting the PR. Can't think of anything else. Oh yeah, both me and @ochawkeye (we're all git heathens though) have commited on our respective forks _after_ submitting PRs which ends up adding them to the PR. A way to get around that is to branch on your fork, which is also cleaner I guess. Well, the same logic still applies, if you commit more to that branch it will be added to the PR too, but then it's probably feature-related at least.

*Any python conventions* My knowledge is to poor here, but if there are any good/reasonable checks that could be made (automated) then I'm all for it.

*Tests* Working as a professional dev (but not in Python unfortunately) this goes without saying. Now however, we're working with a hobby project and I'd hate to see people get scared from contributing because of this but it also makes decisions on accepting/rejecting a PR sooooo much easier. I don't know, maybe say that tests are **strongly** encouraged? :slightly_smiling_face:

**Comment by derek-adair** [comment]
>re tests
Ya i hear that, maybe if we start getting more pull requests it would be good to pass this rule.
